d8ahazard/sd_dreambooth_extension

- dreambooth/train_dreambooth.py
> Honor clip_skip

- scripts/main.py
Resolves #54 (and probably some other dormant bugs)
> Turn integral training parameters into ints (instead of floats)

- requirements.txt
3.9.1 added some breaking changes (that screw up automatic's ui.py)
> Pin gradio version

- dreambooth/conversion.py
Fix "state_dict" problem and use checkpoint_info.filename
> Fix checkpoint load when checkpoint does not have "state_dict"

- dreambooth/conversion.py
- dreambooth/db_config.py
- dreambooth/dreambooth.py
- dreambooth/train_dreambooth.py
https://github.com/d8ahazard/sd_dreambooth_extension/issues/42
> Using webui command line args to set mount path 

- dreambooth/db_config.py
- dreambooth/dreambooth.py
- dreambooth/finetune_utils.py
- dreambooth/train_dreambooth.py
- scripts/main.py
Allow maximum of 300 token length (in fact we can support infinite, but 300 is already enough).
Based on #85 so please merge that first.
Needs some thorough test, I have to touch a lot of stuff to make max token length work. The default of 75 should at least be safe though.
> Feature: increase max token length

- dreambooth/SuperDataset.py
- dreambooth/conversion.py
- dreambooth/db_config.py
- dreambooth/dreambooth.py
- dreambooth/train_dreambooth.py
- dreambooth/v2-inference.yaml
- install.py
- javascript/dreambooth.js
- preload.py
- requirements.txt
- scripts/main.py
- style.css
Add a new SuperDataset class to handle shuffling of training images all the time.
Update UI again, add multiple concept training.
Fix/clean up wizards.
Add a "debugging" panel with various stuff for yours truly, or anybody who wants to play along.
Add better logging of package versions on startup.
Fix various other issues.
Start adding groundwork for V2 model support.
> Add SuperDataset, multiple concepts in the UI, Fixes

- dreambooth/train_dreambooth.py
> Fix ValueError not iterable

- lora_diffusion/lora.py
#498 during saving frequently getting vram exceeded on 6GB system, by changing to a generator this reduces the memory usage.
> partial fix #498 reduce memory usage by changing extract_lora_ups_down to a generator

- dreambooth/train_dreambooth.py
Follow-up to:
https://github.com/d8ahazard/sd_dreambooth_extension/pull/589
hopefully I won't have too many of these.
> Compatibility with python3.8

- requirements.txt
Also update safetensors so be consistent with the webui repo.
> Remove duplicate in requirements

- dreambooth/db_webhook.py
> Small fix for saving and reading webhook url

- dreambooth/finetune_utils.py
- lora_diffusion/lora.py
This should fix inference for sampling with LoRA in the UI.
Before it would throw an error, in this change is more in line with the official repository of using LoRA during inference.
> Fixes LoRA inference for generating samples in the UI.

- dreambooth/finetune_utils.py
I'm not an expert, but I believe this fixes the issue in https://github.com/d8ahazard/sd_dreambooth_extension/issues/768 with backward compatibility for older versions of the webui.
> Support for new CheckpointInfo data structure

- README.md
I have added 4 up-to-date tutorial videos to the readme with 356x200 pixel thumbnails
They are original thumbnails of the videos and directly linking to youtube videos
I am constantly answering every question that comes to the videos
I hope you consider to accept this pull request
My username in discord : MonsterMMORPG#2198
> Adding Several Tutorial Videos To The Readme File

- dreambooth/utils/gen_utils.py
- helpers/image_builder.py
- lora_diffusion/lora.py
Removed LoRA saving for webui for another PR.
> Patch pipe fixes

- dreambooth/train_dreambooth.py
Seeding only works with Shuffle Tags is disabled atm.
> Add set_seed to train_dreambooth.py

- dreambooth/utils.py
Was:
Steps: Steps, CFG scale: CFG scale, Seed: Seed, Size: Size 
Now:
Steps: 60, CFG scale: 7.5, Seed: -1, Size: 512x512
> Fix saving "parameters" in png info

- dreambooth/db_config.py
The JSON only loop top level dict, so it return `concepts_list` and no list
As suppose valid JSON array from extracted `db_config.json`:
```
{
"concepts_list": [
{
"class_data_dir": "",
"class_guidance_scale": 12,
"class_infer_steps": 40,
"class_negative_prompt": "",
"class_prompt": "",
"class_token": "",
"instance_data_dir": "",
"instance_prompt": "",
"instance_token": "",
"is_valid": true,
"n_save_sample": 1,
"num_class_images": 0,
"num_class_images_per": 0,
"sample_seed": 420420,
"save_guidance_scale": 12,
"save_infer_steps": 40,
"save_sample_negative_prompt": "",
"save_sample_prompt": "",
"save_sample_template": ""
}
]
}
```
also issue #903 need to apply in order to work
testing 6 concept, console output:
```
Preparing Dataset (With Caching)
Bucket  0 (512, 256, 0) - Instance Images: …
```
> JSON did not loop "concepts_list" dict

- dreambooth/db_webhook.py
A few variables were misnamed, refactored a small bit too
> Fix for discord webhook

- dreambooth/diff_to_sd.py
Fix bug introduced in https://github.com/d8ahazard/sd_dreambooth_extension/commit/cc9e0098240c2a9dac416e299d091bc21a3dcbc6
> Fix lora model generation

- dreambooth/sd_to_diff.py
- javascript/dreambooth.js
This allows specifying a local clone of an HF repo. Select 'Create from Hub' and specify a folder containing the cloned repo. No token is necessary.
> Feature: allow specifying local clone of HF repo

- dreambooth/dataclasses/db_config.py
- dreambooth/train_dreambooth.py
- javascript/dreambooth.js
- scripts/main.py
Adds offset noise during training as seen here. https://www.crosslabs.org//blog/diffusion-with-offset-noise
> Add offset noise feature

- dreambooth/diff_to_sd.py
- lora_diffusion/lora.py
Change apply lora to use a new merge_lora_to_model method that matches the logic of merge_lora_to_pipe.
Tested change both on extended lora and normal lora (although validation that it is full correct is not easy).
> Update lora ckpt generation to support extended lora

- dreambooth/utils/image_utils.py
Removed underscores, double-spaces, and other characters that will cause file name issues.
This fixes #950
> Fix for class images bad file names

- dreambooth/dataclasses/db_config.py
- dreambooth/train_dreambooth.py
- dreambooth/ui_functions.py
- helpers/image_builder.py
- postinstall.py
- requirements.txt
Hopeful fix bad lora_model_name and stop_text_encoder values.
Also revert diffusers to 0.13.1 (it seems like some people had some issues with it)
> Merge dev to main

- dreambooth/train_dreambooth.py
- helpers/image_builder.py
- javascript/dreambooth.js
> Fix #1011 and re-enable changelog popup

- dreambooth/utils/model_utils.py
Small UX update. Exclude file `changelog.txt`, `revision.txt` and any file in Model `DropDownList` in the future.
-
> List only DB model folder instead of with files

- dreambooth/train_dreambooth.py
- dreambooth/xattention.py
- requirements.txt
- Update to accelerate 0.17.1
- I could not get the new accelerate to work with the recent graph changes so I reverted them
- I also don't think the optim_to is providing and benefits, so I removed that
> Update to accelerate 0.17.1

- dreambooth/sd_to_diff.py
- postinstall.py
> main <- dev (Fix ema extraction)

- README.md
I made the most comprehensive settings comparison - took 3 days to  prepare - new update is just epic
The newest update certainly made this DreamBooth extension the best among all other available scripts. I can say this confidently. No google colab fastben shivam etc can now be compared with d8ahazard. Thank you very much for this amazing update.
Removed one of the outdated video link
Added 2 new videos links. The videos have manually fixed subtitles and fully properly set video sections.
In the first video, I have compared classification image count effect and shown the best settings for 12 GB VRAM having computers
In the second video I have conducted very extensive experiments  The second video, Epic Web UI DreamBooth Update - New Best Settings - 10 Stable Diffusion Training Compared on …
> Updated tutorial links

- dreambooth/train_dreambooth.py
Generating sample images is setting torch.manual_seed which is causing training to do weird things when samples are very frequent. This stores the rng states and restores them so that the training gets close to the same results regardless of the frequency of saving samples.
Before the change, get cyclic errors like this. And epoch is 48.
After change, error graphs look like this:
Note, I get basically the same results with sample frequency 1 and 12.
> Fix samples impacting training.

- dreambooth/dataclasses/db_concept.py
- dreambooth/dataclasses/db_config.py
- dreambooth/dataclasses/prompt_data.py
- dreambooth/dataset/class_dataset.py
- dreambooth/dataset/db_dataset.py
- dreambooth/dataset/sample_dataset.py
- dreambooth/diff_to_sd.py
- dreambooth/optimization.py
- dreambooth/sd_to_diff.py
- dreambooth/train_dreambooth.py
- dreambooth/ui_functions.py
- dreambooth/utils/gen_utils.py
- dreambooth/utils/image_utils.py
- dreambooth/utils/utils.py
- helpers/image_builder.py
- javascript/dreambooth.js
- postinstall.py
- requirements.txt
- scripts/main.py
- Correct class images calculations
- Prevent Dreambooth from changing sliders outside the Dreambooth tab
- Improve install script
- Split the training progress bar from the rest
- Allow negative offset noise
> main <- dev

- dreambooth/dataclasses/db_config.py
- dreambooth/train_dreambooth.py
- dreambooth/webhook.py
- scripts/main.py
Adds option to disable logging graphs, this is useful on training that has a looooot of steps, or for those that just don't want it regardless.
[1035](https://github.com/d8ahazard/sd_dreambooth_extension/issues/1035#issue-1613693708)
- [YES 😉] This is based on the /dev branch (Or a fork of it)
- [YES] This was created or at least validated using a proper IDE
- [YES] I have tested this code and validated any modified functions
- [NO] I have added the appropriate documentation and hint strings if adding or changing a user-facing feature
> Added disable_logging option

- D8-DreamBooth.ipynb
- [ x ] This is based on the /dev branch (Or a fork of it)
- [ x ] This was created or at least validated using a proper IDE
- [ x ] I have tested this code and validated any modified functions
> Colab 'mkdir' Fix

- dreambooth/train_dreambooth.py
- helpers/log_parser.py
- requirements.txt
In the main branch, tensorflow is only intended for log parsing. But it also brings many annoying messages in the terminal. And may cause memory leaks after training.
I found tensorboard **itself** could achieve logging and log parsing. 
See: 
1. https://www.legendu.net/en/blog/read-tensorboard-logs/ 
2. https://github.com/tensorflow/tensorboard/blob/master/tensorboard/backend/event_processing/event_accumulator.py#L210
So I removed tensorflow dependency. And changed the log parsing code. It works very well on the main branch.
> rm tensorflow, use tensorboard for log parsing

- dreambooth/shared.py
- dreambooth/ui_functions.py
- scripts/api.py
1. fix status api invoke error
2. return status as a json object
> fix api error

- dreambooth/train_dreambooth.py
Fixes `ValueError: not enough values to unpack (expected 2, got 1)`
Fix missing values in prior loss variable assignments
The detailed description explains that the prior_loss variable was not assigned properly in certain conditions, resulting in missing values. This commit fixes the code to correctly assign the prior_loss variable when needed.
> ValueError: not enough values to unpack (expected 2, got 1)

- dreambooth/diff_to_sd.py
- dreambooth/sd_to_diff.py
- dreambooth/train_dreambooth.py
- dreambooth/ui_functions.py
- dreambooth/utils/model_utils.py
- helpers/image_builder.py
- javascript/dreambooth.js
- lora_diffusion/lora.py
- postinstall.py
- preprocess/preprocess_utils.py
- requirements.txt
- scripts/main.py
- style.css
Merge Fixes and stuff, maybe people will stop yelling at me.
So many ticket, so much wow.
- [ 😊] This is based on the /dev branch (Or a fork of it)
- [ 😊] This was created or at least validated using a proper IDE
- [ 😊] I have tested this code and validated any modified functions
- [ 😊] I have added the appropriate documentation and hint strings if adding or changing a user-facing feature
> 1.1.0 - Shake Them Haters Off

- dreambooth/train_dreambooth.py
- io/promptHelper.html
- postinstall.py
- scripts/main.py
Thanks, huggingface!
NO.
- [ X] This is based on the /dev branch (Or a fork of it)
- [ X] This was created or at least validated using a proper IDE
- [ X] I have tested this code and validated any modified functions
- [ X] I have added the appropriate documentation and hint strings if adding or changing a user-facing feature
> Fix broken diffusers import

- dreambooth/train_dreambooth.py
Change dimension on the chunk splits of the latents.
!1408
> add fix for sdxl classes

- postinstall.py
added a NoneType check to avoid exception
https://github.com/d8ahazard/sd_dreambooth_extension/issues/1420
- [-] I have added the appropriate documentation and hint strings if adding or changing a user-facing feature
> fixes TypeError: argument of type 'NoneType' is not iterable

- dreambooth/dataclasses/db_config.py
- dreambooth/train_dreambooth.py
- index.html
- javascript/dreambooth.js
- scripts/main.py
- templates/defaults/defaults.json
- templates/defaults/dreambooth_model_config.json
- templates/locales/titles_en.json
This implements DREAM (Diffusion Rectification and Estimation-Adaptive Models) from http://arxiv.org/abs/2312.00210. DREAM helps the model to correct for errors in previous generation steps, at the cost of an additional forward pass during training. Based on my experiments so far it gives greatly improved composition and realism but takes 30%-50% longer per training step.
Example with DREAM:
Control, same training steps and parameters, without DREAM:
- [ + ] This is based on the /dev branch (Or a fork of it)
- [ + ] This was created or at least validated using a proper IDE
- [ + ] I have tested this code and validated any modified functions
- [ + ] I have added the appropriate documentation and hint strings if adding or changing a user-facing feature
> Implement DREAM from http://arxiv.org/abs/2312.00210

- dreambooth/dataset/sample_dataset.py
- dreambooth/train_dreambooth.py
* "Save weights" and "Generate samples" happen immediately
* Generating samples won't try to load every image in the dataset when "[filewords]" is used
* Generating samples handles exceptions reading images for "[filewords]"
* Disables safety checker when generating samples
- [+] This was created or at least validated using a proper IDE
- [+] I have tested this code and validated any modified functions
- [N/A] I have added the appropriate documentation and hint strings if adding or changing a user-facing feature
> Save weights/Generate samples improvements
