d8ahazard/sd_dreambooth_extension

dreambooth/train_dreambooth.py

`RuntimeError: expected scalar type Half but found Float` would occur when no no_cache_latents + no train_text_encoder + fp16.
This fixes #37 
I can confirm it works correctly with the following conditions:
- train_text_encoder, because this line will not be evaluated anyway
- no train_text_encoder + no no_cache_latents + fp16
- no train_text_encoder + no_cache_latents + fp16
I only have 12GB VRAM and cannot afford to test whether it breaks no mixed precision. I truely don't think so because it is already fp32.

Fix expected scalar type Half but found Float.

---

install.py

Thank you for developing this great project!
When I installed this extension, the torch command in `install.py` overwrote my existing `torch==1.13` && `torchvision==1.14` packages. This predictably broke `xformers` and caused my webui installation to break :)
You added the `TORCH_COMMAND` env var to allow for users to define their own torch/torchvision package versions. I have added code in `install.py` to respect the `TORCH_COMMAND` env var.
---
I don't actually know what the intended behavior here is. Is torch/torchvision supposed to be overwritten? Should the user be warned if their torch version is below (not equal?) 1.12+cu116?

Warn user before overwriting torch/torchvision installation

---

dreambooth/train_dreambooth.py

Preview prompt can contain illegal characters such as : or .

Sanitize prompt before using as a filename

---

README.md
dreambooth/train_dreambooth.py

You can use `[filewords]` as placeholder for reading caption from the image filename or a seprarte .txt file containing caption, for example, `[filewords], in the style of zymkyr`. This syntax is the same as textual inversion templates.
You might need to revert commit c1702f13820984a4dbe0f5c4552a14c7833b277e as it is no longer needed. Just using `[filewords]` as instance prompt achieves the same result.
Implement part 1 of #85

Feature: using [filewords] as placeholder.

---

dreambooth/conversion.py

Using same try-except block with cmd_dreambooth_models_path would lead bug when CrossAttention throw exception.

Crossattention try-except block should be individual

---

install.py

No longer use launch because the officially recommended way to invoke subprocesses is through subprocess: https://docs.python.org/3/library/subprocess.html

Switch from launch to subprocess in install.py

---

dreambooth/train_dreambooth.py

Recent changes has broken generated classifier images from saving, at least on Windows PCs

Fixed classifiers throwing path exception on save

---

dreambooth/diff_to_sd.py

If the subdirectory folder has been created once by the checkpoint saving, all other save attempts will fail due to a missing argument in the super-mkdir function

Fix for ckpt saving in subdirectory

---

requirements.txt

Resolves https://github.com/d8ahazard/sd_dreambooth_extension/issues/454 and https://github.com/AUTOMATIC1111/stable-diffusion-webui/issues/5539

Upgrade transformers dependency to v4.25.1

---

scripts/main.py

Fix TypeError: click() missing 1 required positional argument 'outputs'. This should be empty or None, because save_config returns None

Add missed outputs parameter

---

dreambooth/train_dreambooth.py

Using float32 while saving the model weights causes a spike in vram usage while saving. This fixes that. When not using lora, weights are already saved with float16 by default.

Fixed OOM when using lora on a 8GB GPU while saving model weights

---

scripts/main.py

#502 the precision and value had been swapped in the number of training steps (Epoch) field, so was giving a float value of 100 places when it actually needed an int.  Since default value of 100 is typical assume that the intent was value of 100 and precision of 0 (has 1 but again would fail since we need int number of training steps)

fixes #502 training steps per image need to be an int, not a float

---

dreambooth/db_config.py
scripts/main.py

This makes it behave so it does not crash webui. And works as intended.
It basically puts the Checkbox in a disabled state (preventing change events to trigger) till a value is assigned again.
Also fixes it up when 'disabled' values are set in db_config

Fix race condition between use_ema and use_lora as they need to be mutually exclusive

---

dreambooth/db_config.py
dreambooth/diff_to_sd.py
dreambooth/dreambooth.py
dreambooth/train_dreambooth.py
scripts/main.py

Builds off of PR https://github.com/d8ahazard/sd_dreambooth_extension/pull/532
Currently saving checkpoints will use the diffusers name. 
Due to the lora additions, it can be pretty hard to track which projects you're working on.
This adds a textbox field that allows you to enter a custom name. 
If it's empty, it should default to the default saving functionality as before. 
When using lora, it will also name it under the same scheme to better track projects.
Saving and loading params should also be supported properly as well, but let me know if you find any weird edge cases or pitfalls.

Allow saving both lora and checkpoints with custom names

---

dreambooth/train_dreambooth.py

From some discussion on the #548 PR, I was testing the behavior today. 
I then noticed that gradient accumalation was only happening for the first epoch. 
(see  https://github.com/d8ahazard/sd_dreambooth_extension/commit/1426d144cd0bf370d18f8656991730a35deceaf4#commitcomment-93219200 )
Finally tracked this down to the new dataloader created in `cache_latents` and need it to be prepared again so that `accelerator.accumalate` works correctly.

Make sure dataloader is prepared again after caching latents

---

javascript/dreambooth.js
scripts/main.py

Warmup steps applies to all schedulers except the constant without warmup. 
This caused greate confusion testing other schedulers and not realizing the default effectively runs for a long time with the default of 500.

Set warmup steps to 0 by default. Add extra tooltip info on why it could be bad

---

dreambooth/train_dreambooth.py

`save_weights` was set to True even if `save_model` was False, causing checkpoints not the save at times. 
Possibly related issues: #533

Fix issues with not saving checkpoints in certain scenarios

---

dreambooth/finetune_utils.py

Missing the () made the Image Generator create the same image every time despite using [filewords].

Fix Image Generation

---

dreambooth/train_dreambooth.py

Fixes a small mem leak taht was caused by yesterday's grad accum fix PR. 
Accelerate was holding on to references and it would not free up. Causing about 4MB of VRAM to be leaked per epoch.
Also used to simpler version of prepare for just the dataloader.

Fix mem leak

---

dreambooth/diff_to_sd.py

Some implementations of automatic1111 are on python 3.8 instead of 3.10.
This should make the dreambooth extension compatible with those on 3.8.
I am sure there are more compatibility issues but this is the only one I have run into.
Should relieve some of the issues here:
https://github.com/TheLastBen/fast-stable-diffusion/issues/914
Potentially we could just remove the type hints if you wanted to support back to <3.5 but I haven't seen anyone go that far back: 
https://stackoverflow.com/a/63460173

Make backwards compatable with python 3.8

---

dreambooth/db_config.py
dreambooth/train_dreambooth.py
javascript/dreambooth.js
scripts/api.py
scripts/dreambooth.py
scripts/main.py

Instead of using a fixed epoch stop, the text encoder stops training in relation to the epochs to be trained.
If i train 10 epoch, with the ratio at 0.2, the text encode training will be on only the first 2 epochs

Rework of stop text encoder and fix to reported total batch size

---

dreambooth/diff_to_sd.py

LoRA weights weren't saving when going from Diffusers to CKPT. This was resulting in the alphas of `1` being applied twice to the unet if you chose to train the text encoder.
Should resolve some headaches :upside_down_face: .

Fix LoRA text weights not saving.

---

dreambooth/utils.py

While training extensions throws 'FeatureWarning: dropping of nuisance columns in dataframe reductions (with 'numeric_only=none') is deprecated'

Fix Dropping of nuisance columns error

---

configs/v1-inference.yaml
configs/v2-inference-v.yaml
configs/v2-inference.yaml

Can we confirm whether or not that these ***improve*** results? 
The following Stable Diffusion repositories have these enabled, and I feel like enabling these are giving me better results on LoRA training. I *have not* tested this with regular Dreambooth, but I would expect the same.
If this is indeed the case, it would probably be smarter to create separate configs for training (the keys with *this* change) and leave the inference before this change.
_[Dreambooth-Stable-Diffusion](https://github.com/XavierXiao/Dreambooth-Stable-Diffusion/blob/main/configs/stable-diffusion/v1-finetune_unfrozen.yaml)
[Custom Diffusion](https://github.com/adobe-research/custom-diffusion/blob/26ba6388235ec7b636e38d8bc368ac7243036ae7/configs/custom-diffusion/finetune.yaml#L92)
[textual_inversion …

Update YAML configs to enable proper training 

---

javascript/dreambooth.js
scripts/api.py
scripts/main.py

With larger datasets, increasing this seems to yield better results if you're willing to have larger files, especially with the latest `.yaml` changes.
If you've ever used hypernetworks in the webui, the resulting file at maximum is similar, but more information is retained if you have a very complex dataset with many images.
This is a great alternative to PTI which will lead to great results at the default settings, but it's not implemented yet.
More information can be found here https://github.com/cloneofsimo/lora/discussions/37 .

LoRA Rank info and increase maximum settable rank in UI.

---

dreambooth/finetune_utils.py

Using the boolean from `getexif()` isn't enough. This ensures that this part goes through if exif data isn't found for an image file.

Fix crash on exif check.

---

dreambooth/finetune_utils.py
lora_diffusion/lora.py

Changes to the `patch_pipe` function to generate image samples when using LoRA weights.
The custom `apply_lora_weights` functions are no longer needed.

Use patch pipe for generating LoRA samples.

---

requirements.txt

Installing on an M1 I got `No module named tensorflow` errors (see #751).
With this change we can install the desired requirements on all supported platforms.
thanks

Fix tensorflow requirement macosx M1

---

scripts/api.py

I opened https://github.com/d8ahazard/sd_dreambooth_extension/issues/837 recently, and I was able to fix the problem. The Form and Body parameters are not compatible.
Therefore I replaced the Form parameters with a Header one.

Update API: fixing POST /dreambooth/model_config

---

dreambooth/dataset/db_dataset.py

Missing the `eos_token` param.

Add param to strict tokens

---

dreambooth/dataset/db_dataset.py

Currently we only shuffle at the start and not between epochs. I verified that we are only calling __getitem__ (and by extension shuffling the tags) only once per epoch even if batch > 1

re-add tag shuffling

---

lora_diffusion/lora.py

This is a fix for #957 where training cannot be resumed from LoRA weights due to the exception:
```
TypeError: cannot assign 'torch.FloatTensor' as parameter 'weight' (torch.nn.Parameter or None expected)
```
To resolve it, I changed
```python
if loras is not None:
_module._modules[name].lora_up.weight = loras.pop(0)
_module._modules[name].lora_down.weight = loras.pop(0)
```
to
```python
if loras is not None:
_module._modules[name].lora_up.weight = nn.Parameter(loras.pop(0))
_module._modules[name].lora_down.weight = nn.Parameter(loras.pop(0))
```
Issue is #957.

Fix resuming training from LoRA weights failing with an exception

---

dreambooth/train_dreambooth.py

Sometime, loading a saved settings for training, revision comes as string, which leads to errors when math is done on it (calculating steps). This help ensure revision is int before its being used.
- [x ] This is based on the /dev branch (Or a fork of it)

Ensure args.revision int

---

postinstall.py

`grep` is Unix command that not exist on Windows without installing GnuWin.
Perhaps using `findstr`, but python it self has better option.
This code runs any Operating System (Windows, Linux, macOS, ...)
-

grep not exist on Windows without GnuWin

---

helpers/image_builder.py

Fixes TypeError: join() argument must be str, bytes, or os.PathLike object, not 'list' error when generating images without lora. The previous code attempted to construct the path while lora_model = null.

Fix image builder breaking when use_lora is false and lora_model is null

---

dreambooth/dataclasses/db_config.py
dreambooth/diff_to_sd.py
dreambooth/shared.py
dreambooth/train_dreambooth.py
dreambooth/ui_functions.py
dreambooth/utils/model_utils.py
javascript/dreambooth.js
lora_diffusion/extra_networks.py
lora_diffusion/lora.py
postinstall.py
requirements.txt
scripts/api.py
scripts/main.py

When option is selected, when saving loras (modelname_steps.pt) we will also save modelname_steps.safetensors that is compatible with a1111 extra networks.
This change implements a new safetensor format for loras.
- It does not support extended lora
- We move .pt file generation to a new folder db_loras configured as db_lora_models_path. Introduce ui_lora_models_path for extra networks models.

Implement option to save extra_networks lora.py

---

dreambooth/dataset/class_dataset.py

Fixes a bug when creating classification images with [filewords] in the class prompt.
Currently if the class prompt contains "[filewords]", then the instance prompt is added to the class prompt in place of "[filewords]" when creating class images:
These changes will add the [filewords] from instance images in place of "[filewords]" in class prompts when creating class images:

Fix filewords in class prompt

---

dreambooth/dataclasses/db_config.py

The model_name is getting passed in as a single element list for me.  The existing code doesn't handle that case, sanitize_name ends up returning an empty string, then open() throws because the db_config.json doesn't exist in the wrong path.
I don't know the root cause of this issue, maybe some of the automatic1111 UI library updates changed some behavior here.
- Adds a line to handle the case I'm seeing, where model_name is a list.
- Based on main (currently ahead of dev)

Fix/workaround for model_name being a list

---

dreambooth/utils/image_utils.py

This PR refactors the `dreambooth/utils/image_utils.py` file by improving the handling of image orientation using EXIF data. A new function `rotate_image_straight` is introduced to handle the image rotation based on the EXIF orientation tag.

fix: rotate input images base on exif orientation

---

dreambooth/dataclasses/db_config.py
dreambooth/diff_to_sd.py
dreambooth/optimization.py
dreambooth/sd_to_diff.py
dreambooth/train_dreambooth.py
dreambooth/train_imagic.py
dreambooth/ui_functions.py
dreambooth/utils/model_utils.py
helpers/image_builder.py
index.html
javascript/dreambooth.js
js/module_dreambooth.js
module_dreambooth.py
scripts/api.py
scripts/main.py

Since the LoRA training does not mutate the base model, there is no reason to be copying 4GB of models every time we train. In this change, we add a new checkout to the Create UI which exposes a new AI to allow using a shared source diffusers model.
I have tested a bunch of training mostly v1.5 models, but I at least tried creating models on 2.1. I have not tried hub models, they might not work.
I probably need to write some documentation for this if it seems useful. Maybe I should move this into a new branch and have people try it.

Allow LoRA model training to use shared diffusers models

---

dreambooth/utils/image_utils.py

Flatten each channel instead of removing Alpha Channel entirely, this should fix bleeding colour, hollow and bad anti-aliasing.
Tested image format/codec with Transparent:
* PNG
* WebP
* AVIF
* TGA (Game Texture)
About preprocess game texture like DXT5 require `import pyglet` which is not needed at the moment or never, it's better convert DXT instead of reading directly...
| Input |  RGB Convert | Flatten |
|-------|---------------|---------|
| ![data pak_000158](https://user-images.githubusercontent.com/1908715/230780389-ad242a63-598e-4ed2-b1ed-a38b6ad32b32.png) | ![Remove Alpha Channel](https://user-images.githubusercontent.com/1908715/230779306-005c34e0-5ffa-4efa-b579-3b019246cd44.png) | ![Flatten](https://user-images.githubusercontent.com/1908715/230779312-7ac8bfdb-e4fa-40fc-866d-db864 …

Process Alpha Channel (Transparency) by Flatten it

---

dreambooth/dataclasses/db_config.py

Automatically rebuild path from where folder JSON is reside and `concat` path that defined, allow user share dataset without needing to edit the JSON. No need to use absolute/rooted path on `instance_data_dir`.
```
E:\dataset\fallenAngel
├───ConceptList.json
├───Anime
│   ├───Aho-Girl
│   │   ├───Akutsu Ruri
│   │   ├───Eimura Akane
│   │   ├───Fuuki Iinchou
│   │   ├───Hanabatake Yoshiko
│   │   └───Sumino Sayaka
│   ⁞
│   ├───Liza Luna
│   ├───Shiina Mahiru
│   └───Yuru Yuri
│       ├───Akaza Akari
│       ├───Funami Yui
│       └───Toshinou Kyouko
⁞
```
```json
[
{
"class_data_dir": "",
"class_guidance_scale": 12,
"class_infer_steps": 20,
"class_negative_prompt": "lowres, bad anatomy, bad hands, text, error, missing fingers, extra digit, fewer digits, cropped, worst quality, low …
```

Make Concept List file portable!

---

dreambooth/train_dreambooth.py
helpers/image_builder.py

Attempt to fix
```st
File "...\sd_dreambooth_extension\dreambooth\train_dreambooth.py", line 973, in save_weights
s_pipeline = DiffusionPipeline.from_pretrained(
File "...\site-packages\diffusers\pipelines\pipeline_utils.py", line 1039, in from_pretrained
loaded_sub_model = load_sub_model(
File "...\site-packages\diffusers\pipelines\pipeline_utils.py", line 445, in load_sub_model
loaded_sub_model = load_method(os.path.join(cached_folder, name), **loading_kwargs)
File "...\site-packages\diffusers\models\modeling_utils.py", line 583, in from_pretrained
raise ValueError(
ValueError: Cannot load <class 'diffusers.models.unet_2d_condition.UNet2DConditionModel'> from ...\AppData\Local\Temp\tmpz5b_v_5g\unet because the following keys are missing: 
up_blocks.1.resnets.2.conv2.weight, …
```

Quick fix for checkpoint saving error

---

requirements.txt

Bumped the version of `transformers` in requirements.txt to version `4.30.1` to resolve an issue with sample image generation during training.
https://github.com/d8ahazard/sd_dreambooth_extension/issues/1275

Bump transformers to 4.30.1 to fix BFloat16 error with sample image generation

---

requirements.txt

Bumped the version of `transformers` in requirements.txt to version `4.30.1` to resolve an issue with sample image generation during training.
https://github.com/d8ahazard/sd_dreambooth_extension/issues/1275

[HOT-FIX] Bump transformers to 4.30.1 to fix BFloat16 error with sample image generation

---

helpers/image_builder.py

The code was using the LORAs directory instead of the .pt file path. This obviously didn't work, and triggered an assert in `_text_lora_path_ui()`.
- [+] This is based on the /dev branch (Or a fork of it)
- [+] This was created or at least validated using a proper IDE
- [+] I have tested this code and validated any modified functions
- [N/A] I have added the appropriate documentation and hint strings if adding or changing a user-facing feature

Fix sample generation with LORA

---

scripts/api.py

Model creation via the REST API is no longer working after the recent training changes due to `is_512` being replaced by `model_type`.  This PR resolves the issue so that models can once again be created using the REST API.

[HOT-FIX] Fix creating a model via the REST API

---

dreambooth/diff_to_sd.py

reshape_weight_for_sd() was being applied to biases as well as weights.
This is not the most elegant fix, but it is the simplest.
Fixes convert_vae_state_dict() to not add extra size-1 dimensions to the biases when renaming to_q -> q etc.
https://github.com/d8ahazard/sd_dreambooth_extension/issues/1405
https://github.com/d8ahazard/sd_dreambooth_extension/issues/1407
- [ dev is stale ] This is based on the /dev branch (Or a fork of it)
- [ + ] This was created or at least validated using a proper IDE
- [ + ] I have tested this code and validated any modified functions
- [ N/A ] I have added the appropriate documentation and hint strings if adding or changing a user-facing feature

Fix VAE checkpoint export

---

dreambooth/utils/image_utils.py

An exception while reading an image (such as PIL.Image.DecompressionBombError) during precache causes the entire training run to fail with an unhelpful error that doesn't even say what file didn't load. Instead, skip images that didn't load.
- [ + ] This was created or at least validated using a proper IDE
- [ + ] I have tested this code and validated any modified functions
- [ N/A ] I have added the appropriate documentation and hint strings if adding or changing a user-facing feature

Skip images which failed to load

---

dreambooth/dataclasses/db_config.py
dreambooth/train_dreambooth.py
helpers/ema_model.py
index.html
javascript/dreambooth.js
scripts/main.py
templates/defaults/defaults.json
templates/defaults/dreambooth_model_config.json
templates/locales/titles_en.json

See https://arxiv.org/abs/2303.06296
This adds an option to reparametrize the model weights using the spectral norm so that the overall norm of each weight can't change. This helps to stabilize training at high learning rates.
- [+] This was created or at least validated using a proper IDE
- [+] I have tested this code and validated any modified functions
- [+] I have added the appropriate documentation and hint strings if adding or changing a user-facing feature

Add freeze_spectral_norm option

---

dreambooth/train_dreambooth.py

Fixes DREAM when used with v-prediction models. The paper only did the math for epsilon prediction, and my original v-prediction version had a serious bug.
- [ x ] This was created or at least validated using a proper IDE
- [ x ] I have tested this code and validated any modified functions
- [ N/A ] I have added the appropriate documentation and hint strings if adding or changing a user-facing feature

Fix DREAM for v-prediction

---

dreambooth/dataset/class_dataset.py
dreambooth/dataset/db_dataset.py
dreambooth/train_dreambooth.py
dreambooth/utils/gen_utils.py
dreambooth/utils/image_utils.py

Pillow (PIL) supports lazy loading of images, where the actual image data is only loaded when needed. Currently `image_utils.get_dim()` loads the image data to handle EXIF rotations. There's no need to do that, we can just swap width and height if necessary. This gives a ~4x speedup in preload when the latents are already cached.
- [+] This was created or at least validated using a proper IDE
- [+] I have tested this code and validated any modified functions
- [N/A] I have added the appropriate documentation and hint strings if adding or changing a user-facing feature

Speed up preprocessing

---

dreambooth/train_dreambooth.py
helpers/ema_model.py

EMA saving was broken if `ema_unet/diffusion_pytorch_model.safetensors` already existed. This changes `safe_serialization` to `True` and removes the weird workaround in `ema_model.save_pretrained`.

Fix saving EMA model
